apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "windowsExporter.name" . }}-scripts
  namespace: {{ template "windowsExporter.namespace" . }}
  labels: {{ include "windowsExporter.labels" . | nindent 4 }}
data:
  copy-binary.ps1: |-
{{ .Files.Get "scripts/copy-binary.ps1" | indent 4 }}
  proxy-entry.ps1: |-
{{ .Files.Get "scripts/proxy-entry.ps1" | indent 4 }}
