template: staging

sync:
- url: https://github.com/rancher-sandbox/hypper-charts.git
  branch: main
validate:
- url: https://github.com/rancher-sandbox/hypper-charts.git
  branch: main
  dropReleaseCandidates: true
helmRepo:
  cname: charts.hypper.io