annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: vSphere CPI
  hypper.cattle.io/namespace: kube-system
  catalog.cattle.io/os: linux
  hypper.cattle.io/release-name: vsphere-cpi
apiVersion: v1
appVersion: 1.0.0
description: vSphere Cloud Provider Interface (CPI)
icon: https://charts.rancher.io/assets/logos/vsphere-cpi.svg
keywords:
- infrastructure
maintainers:
- email: caleb@rancher.com
  name: Rancher
name: rancher-vsphere-cpi
sources:
- https://github.com/kubernetes/cloud-provider-vsphere
version: 1.0.000
