vCenter:
  host: ""
  port: 443
  insecureFlag: "1"
  datacenters: ""
  username: ""
  password: ""
  credentialsSecret:
    name: "vsphere-cpi-creds"
    generate: true

cloudControllerManager:
  image:
    repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
    tag: v1.2.1
  nodeSelector: {}

global:
  cattle:
    systemDefaultRegistry: ""
