dependencies:
- name: grafana
  version: ""
  repository: file://./charts/grafana
  condition: grafana.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: k3sServer
  version: ""
  repository: file://./charts/k3sServer
  condition: k3sServer.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: kube-state-metrics
  version: ""
  repository: file://./charts/kube-state-metrics
  condition: kubeStateMetrics.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: kubeAdmControllerManager
  version: ""
  repository: file://./charts/kubeAdmControllerManager
  condition: kubeAdmControllerManager.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: kubeAdmEtcd
  version: ""
  repository: file://./charts/kubeAdmEtcd
  condition: kubeAdmEtcd.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: kubeAdmProxy
  version: ""
  repository: file://./charts/kubeAdmProxy
  condition: kubeAdmProxy.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: kubeAdmScheduler
  version: ""
  repository: file://./charts/kubeAdmScheduler
  condition: kubeAdmScheduler.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: prometheus-adapter
  version: ""
  repository: file://./charts/prometheus-adapter
  condition: prometheus-adapter.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: prometheus-node-exporter
  version: ""
  repository: file://./charts/prometheus-node-exporter
  condition: nodeExporter.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: rke2ControllerManager
  version: ""
  repository: file://./charts/rke2ControllerManager
  condition: rke2ControllerManager.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: rke2Etcd
  version: ""
  repository: file://./charts/rke2Etcd
  condition: rke2Etcd.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: rke2Proxy
  version: ""
  repository: file://./charts/rke2Proxy
  condition: rke2Proxy.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: rke2Scheduler
  version: ""
  repository: file://./charts/rke2Scheduler
  condition: rke2Scheduler.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: rkeControllerManager
  version: ""
  repository: file://./charts/rkeControllerManager
  condition: rkeControllerManager.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: rkeEtcd
  version: ""
  repository: file://./charts/rkeEtcd
  condition: rkeEtcd.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: rkeProxy
  version: ""
  repository: file://./charts/rkeProxy
  condition: rkeProxy.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: rkeScheduler
  version: ""
  repository: file://./charts/rkeScheduler
  condition: rkeScheduler.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: windowsExporter
  version: ""
  repository: file://./charts/windowsExporter
  condition: windowsExporter.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
