annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Rio
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/hidden: "true"
  hypper.cattle.io/namespace: rio-system
  hypper.cattle.io/release-name: rio
  catalog.cattle.io/requires-gvr: networking.istio.io.virtualservice/v1beta1
apiVersion: v1
appVersion: 0.8.0
description: The application deployment engine for Kubernetes
home: https://rio.io
icon: https://charts.rancher.io/assets/logos/rio.svg
name: rio
version: 0.8.001
