overlayFile: ""
tag: 1.8.3
##Setting forceInstall: true will remove the check for istio version < 1.6.x and will not analyze your install cluster prior to install
forceInstall: false

installer:
  repository: rancher/istio-installer
  tag: 1.8.3-rancher1

istiocoredns:
  enabled: false
  image:
    repository: rancher/mirrored-coredns-coredns
    tag: 1.6.2
  pluginImage:
    repository: rancher/mirrored-istio-coredns-plugin
    tag: 0.2-istio-1.1

base:
  enabled: true

cni:
  enabled: false
  repository: rancher/mirrored-istio-install-cni
  tag: 1.8.3
  logLevel: info
  excludeNamespaces:
  - istio-system
  - kube-system

egressGateways:
  enabled: false
  type: NodePort

ingressGateways:
  enabled: true
  type: NodePort

istiodRemote:
  enabled: false

pilot:
  enabled: true
  repository: rancher/mirrored-istio-pilot
  tag: 1.8.3

telemetry:
  enabled: true
  v2:
    enabled: true

global:
  cattle:
    systemDefaultRegistry: ""
  proxy:
    repository: rancher/mirrored-istio-proxyv2
    tag: 1.8.3
  proxy_init:
    repository: rancher/mirrored-istio-proxyv2
    tag: 1.8.3
  defaultPodDisruptionBudget:
    enabled: true

# this can be removed in 1.7 as it is default
meshConfig:
  enablePrometheusMerge: true

# Kiali subchart from rancher-kiali-server
kiali:
  enabled: true
  auth:
    strategy: anonymous
  deployment:
    ingress_enabled: false
    repository: rancher/mirrored-kiali-kiali
    tag: v1.29.0
  external_services:
    prometheus:
      custom_metrics_url: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090"
      url: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090"
    tracing:
      in_cluster_url: "http://tracing.istio-system.svc:16686/jaeger"
    grafana:
      in_cluster_url: "http://rancher-monitoring-grafana.cattle-monitoring-system.svc:80"
      url: "http://rancher-monitoring-grafana.cattle-monitoring-system.svc:80"

tracing:
  enabled: false
  contextPath: "/jaeger"
  jaeger:
    repository: rancher/mirrored-jaegertracing-all-in-one
    tag: 1.20.0
