{{- if .Values.additionalLoggingSources.rke2.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rke2
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
data:
  fluent-bit.conf: |
    [INPUT]
        Name              systemd
        Tag               rke2
        Systemd_Filter    _SYSTEMD_UNIT=rke2.service

    [OUTPUT]
        Name              forward
        Match             *
        Host              {{ .Release.Name }}-fluentd.{{ .Release.Namespace }}.svc
        Port              24240
        Retry_Limit       False
{{- end }}
